### PR TITLE
docs: bump pdf stable version to release-7.5

### PR DESCRIPTION
**Pull request by Oreoxmt**
Update the stable PDF version of TiDB and TiDB Cloud:

- TiDB: the stable PDF version is updated from release-7.1 to release-7.5.
- TiDB Cloud: the stable PDF version will remain at release-7.1 to ensure consistency with the current TiDB Cloud documentation.

### CODE REVIEW

**Comment by purelind** [comment]
> /cc @Yuiham

Is this PR ready to be merged?

**Review by Yuiham — APPROVED** [review]
LGTM

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
