### PR TITLE
tikv-migration: Change to go1.18

### PR DESCRIPTION
**Pull request by pingyu**
Signed-off-by: pingyu <yuping@pingcap.com>

# Changes
1. Change to go1.18.
2. Add release branch named as `cdc-xxx`.
3. Remove other CI tasks using Github action.

### CODE REVIEW

**Comment by pingyu** [comment]
@haojinming @zeminzhou PTAL~

**Review by haojinming — APPROVED** [review]
LGTM~

**Review by zeminzhou — APPROVED** [review]
LGTM~

**Comment by pingyu** [comment]
@purelind PTAL, thanks~

**Review by purelind — APPROVED** [review]
LGTM

**Pull request merged**
